# Site settings
title:       Gerard Paredes
email:       gerard.paredes.piera@gmail.com
author:      Gerard Paredes
baseurl:     ""
url:         "http://www.gparedes.com"
date_format: "%b %-d, %Y"
description: Un blog d'enginyeria mecànica.

# Jekyll settings
plugins:
  - jekyll-paginate
  - jekyll-gist

# Google services
google_analytics: UA-124634937-1
google_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footer:    true
show_rss:             true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax:       true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: gerards-blog

# Social icons
github_username:
stackoverflow_id: 
twitter_username:
linkedin_username: gerard-paredes
bitcoin_url:
paypal_url: 

# Post sharing icons
share_text:
show_sharing_icons: true
share_facebook: 	true
share_twitter: 		true
share_googleplus: 	true
share_linkedin: 	true
share_tumblr: 		true
share_reddit: 		true
share_stumbleupon:	true
share_hackernews: 	true

# Build settings
markdown:     kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink:    pretty
paginate:     4
sass:
  compressed: true

# Additional settings
include: ['_pages']
